### ISSUE TITLE
Constants errors in wozfp.s

### ISSUE THREAD

**Issue by markjfisher** [jefftranter/6502#10]
I'm yet another developer implementing the Steve Wozniak FP routines printed in Dr Dobb's Journal 1976.

However, also as a mathematician, I was checking the FP constants in the code and I noticed some errors.

In the text file that I was basing my work on (http://www.6502.org/source/floats/wozfp1.txt) I tried to calculate by hand the constants and found that several of them are wrong.

I found a copy of the original print at https://archive.org/details/dr_dobbs_journal_vol_01/page/n209/mode/2up

It looks like the digits were read incorrectly, as they are close but not equal to the original print

![image](https://user-images.githubusercontent.com/1616940/97779752-25416400-1b78-11eb-9c24-fd7d56f411cb.png)

Text: R22 = 80 5A 02 7A
Orig: R22 = 80 5A 82 7A

These are easily checked, the value is 2^(x80- high byte) * (lower 3 bytes) / 2^22
5A027A = 1.4064012
5A827A = 1.4142136

Similarly for A1:
Text: A1 = 80 52 80 40
Orig: A1 = 80 52 B0 40

Again, very similar, but the text 8 was actually a B
Changing the expected value of A1 from 1.2920074 down to 1.289077759

So a patch would be:

```
R22:   .byte $80, $5A, $82, $7A ; 1.4142136 SQRT(2)

LE2:   .byte $7F, $58, $B9, $0C ; 0.69314718 LOG BASE E OF 2

A1:    .byte $80, $52, $B0, 40 ; 1.2920074
```

**Comment by markjfisher** [comment]
There is in fact a version that gets the constants correct at:
http://www.easy68k.com/paulrsm/6502/WOZFPIA.TXT

**Comment by jefftranter** [comment]
Thanks, I have applied the changes to the source on github.

**Comment by jefftranter** [comment]
Fixed.
