### ISSUE TITLE
JMON info.s can corrupt top of memory code

### ISSUE THREAD

**Issue by w4jbm** [jefftranter/6502#13]
In the info.s module of JMON, the code tests memory byte by byte starting at an address stored and maintained at $0000.

The code doing the testing tries to protect itself from having the test walk through it by skipping over the page (or pages) where the top-of-memory search code are:

```
        LDA TOP+1           ; High byte of page
        CMP #>FindTopOfRAM  ; Same page as this code?
        BEQ @Skip
        CMP #>FindTopOfRAMEnd ; Same page as this code (code could cross two pages)
        BEQ @Skip
        BNE @NotUs
@Skip:
        INC TOP+1           ; Skip over this page when testing

@NotUs:

        LDA TOP+1           ; Did we reach LIMIT? (high byte)
        CMP #>LIMIT
        BNE @Loop           ; If not, keep looping
        LDA TOP             ; Did we reach LIMIT? (low byte)
        CMP #<LIMIT
        BNE @Loop           ; If not, keep looping
```
If this code actually crosses two pages, the test on the second page does not take place. For example, if the code is on Page X and Page Y, the first compare will determine it is on Page X, increment it (so it now points to Page Y), and then jump back to @NotUS and continue testing.

If the code crosses two pages, it seems like it will always only skip only the first. (And if the code is all on one page, the test is redundant but that doesn't cause any issue.)

It is a bit of a bandaid, but what I did was change the code to this:
```
        LDA TOP+1           ; High byte of page
        CMP #>FindTopOfRAM  ; Same page as this code?
        BEQ @Skip
        BNE @NotUs
@Skip:
        INC TOP+1           ; Skip over this page when testing
        INC TOP+1
```
I only test for the first page (Page X in my example) and then I increment not once but twice, so I always skip both the page where the code begins and the page following that.

If this code were towards the top of memory, it might need a more elegant fix (maybe do the comparison to the page where the code ends minus 1 so you always skip the end of the code and the page that precedes it if needed).

I was encountering "hangs" of the test before the change, but it crosses two pages and runs fine now.

**Comment by jefftranter** [comment]
Thanks, I commited this fix.
