### ISSUE TITLE
A1 BASIC relocation

### ISSUE THREAD

**Issue by w4jbm** [jefftranter/6502#16]
The A1 BASIC as it is will not assemble and standalone if you try to relocate the code. There are hard coded references to the pages used in the code and in certain tables. It will work (and largely use the relocated code for things at times) if there is an still an image of A1B at $E000. To make it truly stand alone, the following changes are needed.

Line 96, change to the origination address (to be safe and keep thing easy, I keep this at a multiple of $2000).

Line 200, the LDX #$ED needs to load the second page of the token table is located. The code will check if you are looking for a token greater than $50, it will the page further down in the code. (The tokens are parsed downward from the highest memory address which contains information of the lowest number token.)

Line 761, the LDA #$76 is followed by an ROL (effectively doubling it), so this is actually a pointer to page $EC. This is why I believe that you need to stick to even pages as origins (and would, for extra safety, stick with multiples of $2000). If you want to relocate to $8000, you need to change line 761 to LDA #$46. For relocation to $A000, it become LDA #$56.

Lines 1520 through 1544 contain a table of the high-byte of the addresses of functions in the verb table. All of the addresses in the $E0 thru $EF would need to changed to reflect the address things are relocated to. (For example, the first $E8 would need to become $88 to move the code to $8000. The $FF values seem to be markers that don't actually point to an address, so they can remain unchanged.)

By sticking to multiples of $2000, you can just do a search and replace for something like find '$E' and replace with '$8' in the tables. If you move it to some other type of page boundary, there would, at a minimum, be a lot more math involved.

With these changes and patches to the I/O routines, I was able to get this running on a PAL-1/KIM-1 at $8000 (in RAM) and $A000 (in ROM).

I wrote two short Python program to help automate it (on my GitHub page in the A1B repository), but actually modifying the source to automatically calculate the values that need to be changed would be a better approach if someone is going to be doing much relocation.

Even with needing this tweak, I never would have gotten A1B running without your source code. Thanks!

**Comment by jefftranter** [comment]
Thanks for this information. I've updated the code with some comments on relocation and adjusted the syntax table to  refer to labels so it should, in theory, now be relocatable.
