### ISSUE TITLE
Minor error in port of Apple ][ System Monitor

### ISSUE THREAD

**Issue by svhum** [jefftranter/6502#18]
I believe there may be an error in this port of the Apple ][ System Monitor. Line 1999 reads:
`IOPRT1: LDA COUT1/256`
This attempts to load the accumator with the high byte of the address of subroutine `COUT1`. This is actually using a zero-page addressing mode since `COUT1/256` evaluates to a byte and there is no hash to indicate to load immediate. I believe the correct line should read:
`IOPRT1: LDA #>COUT1`

This may result in the I/O vectors being loaded with the wrong address on an Apple II, if for some reason the monitor is relocated.

This correction also matches what appears in the [original F8 ROM](https://6502disassembly.com/a2-rom/OrigF8ROM.html).

Out of curiosity, the `IOPRT2` routine seems to require that `LOC0` and `LOC1` be initialized to 0 and 1, respectively. This does not seem to be set anywhere in the monitor. Was this done somewhere else on the Apple II computers?

**Comment by jefftranter** [comment]
You are correct. Thanks for noticing this. I have fixed it in the source code.
According to "What's Where in the Apple", LOC0 and LO1 get initialized on the Apple II computers, but I do not know where off the top of my head.
