### ISSUE TITLE
Typo in the Cassette Load and Save section of KIM-1 Quick Reference

### ISSUE THREAD

**Issue by Robert-Di-Benedetto** [jefftranter/6502#20]
The 1st instructions in both the Save and Load sections specify to store value $00 in $00F1 which resets the Decimal mode flag.  This is correct however it is to ensure that the CPU is in BINARY mode.  The comments incorrectly state it is to ensure the CPU is in Decimal mode.

**Comment by jefftranter** [comment]
Thanks for noticing this. I have corrected it.
