### ISSUE TITLE
Invalid character in path name

### ISSUE THREAD

**Issue by MikeMnemonic** [jefftranter/6502#26]
Hello Jeff,

I'm interested in using your JMON as a basis of a test ROM. However .. the git fails to clone due to (I think) a bad character in a path.

'basic/OSI/disk1/BEXEC*'

I've downloaded the ZIP and this is missing or ignored when expanded.

I'm using windows 11. Google says that this is file name is acceptable in LINUX.

Regards,

Mike (UK)

**Comment by jefftranter** [comment]
I've renamed these files to BEXEC.
