### ISSUE TITLE
HEXPAWN

### ISSUE THREAD

**Issue by Kokovec** [jefftranter/6502#7]
;	Formatted for the SB-Assembler-3 (sbasm v3)
; https://www.sbprojects.net/sbasm/index.php	
	
	.CR	6502
	.TF   hexpawn_0100.BIN,BIN
	.EF errors
	.OR $0100

	
;KIMROM routines
PADD		.EQ $1741
CONVD		.EQ $1F4E-6
KEYIN		.EQ $1F40
GETKEY		.EQ $1F6A
SCANDS		.EQ $1F1F
DIGCOD		.EQ $1FE7
TIMER       .EQ $1704

; Page 0 locations used by program HEXPAWN
FLSHR 		.EQ $0000	;Timer for flashing KIM's men 
DBD	  		.EQ $0001	;Current board in Display format
MASK		.EQ	$0004	;Masks for flashing KIM's men 
EBD			.EQ	$0007	;Current bd - Easy-to-read format
WINDO		.EQ	$0010	;Current 7-segment display
MOVTIM		.EQ $0016
MOVTYP		.EQ	$0017	;KIM's last move (TO;FROM)
TOG			.EQ	$0018	;On/Off indicator for KIM's men
GAMNUM		.EQ	$0019	;Game number
BDNDX		.EQ	$001A	;3*Bd # for model match/move select
MOVNO		.EQ	$001B	;KIM's last move # (0,1, or 2)
PTO			.EQ	$001C	;Person's last "to" move
FROM		.EQ	$001D	;If < 0, no "from" move yet
						;If >= 0, is equal to the "from" move
TMP			.EQ	$001E
TMP1		.EQ	$001F
POINTER		.EQ $0020
POINT0		.EQ	$0021	;Page # (ADH) of MOVES
MPOINT		.EQ	$0022
MPOIN1		.EQ $0023	;page # (ADH) of messages
BGEBD		.EQ	$0024	;Beginning bd - Easy-format:
						;	03 = KIM
						;	00 = space
						;	01 = Person
MOVES		.EQ	$002D	;Table of possible moves is placed
						;here by startup routine and
						;is modified as KIM "learns"
INH			.EQ	$00F9
TEMP		.EQ $00FC
			

;HEXPAWN for KIM-1 Copyright May 1978 R.C. Leedom

HXPNST	LDX	#$6E			;transfer moves, beginning
INLP
		LDA	SP0IN0,X
		STA	POINT0,X
		DEX
		BPL INLP
		STA GAMNUM
		JMP	INIT

;The following board positions that
;the HEXPAWN program will recognize after the
;human opponent has moved. The squares are numbered
;according to the scheme shown in the
;comment field for CAPSET (location 03F8)
;Here, the pieces and spaces (K=KIM, P=person,
;and _=space) are packed by column -- that is,
;in gorups: 0,3,6; 1,4,7; 2,5,8, (For segment-
;lighting, actual data is ordered 360,471,582)
BDMDL
	.DB $43, $0B, $0B	;KP_,K_P,K_P
	.DB	$0B, $0B, $43	;K_P,K_P,KP_
	.DB $0B, $43, $0B	;K_P,KP_,K_P
	.DB $C3, $40, $0B	;KK_,_P_,K_P
	.DB $40, $C3, $0B
	.DB	$43, $48, $03
	.DB	$43, $03, $48
	.DB $08, $C3, $43
	.DB $C8, $43, $43
	.DB $C3, $08, $43
	.DB $43, $43, $C8
	.DB $48, $03, $43
	.DB $40, $40, $43
	.DB $08, $43, $03
	.DB $43, $00, $0B
	.DB $C0, $C0, $43
	.DB $43, $40, $40
	.DB $C0, $43, $40
	.DB $40, $43, $C0
	.DB $C3, $C0, $40
	.DB $43, $08, $C3
	.DB $00, $43, $0B
	.DB $40, $C0, $C3
	.DB $C0, $40, $03
	.DB $40, $C3, $00
	.DB $00, $C3, $40
	.DB $0B, $00, $43
	.DB $00, $40, $C3
	.DB $0B, $40, $C3
	.DB $03, $48, $43
	.DB $43, $C8, $43
	.DB $00, $43, $00
	.DB $C3, $40, $00
;End-game messages
KWIN
	.DB $3E, $00, $38, $3F, $6D, $79
PWIN
	.DB $00, $54, $1C, $78, $6D, $00
KWAD	.EQ	KWIN-$100
PWAD	.EQ	PWIN-$100
;The following data is saved here for startup intitalization
SP0IN0	.DB	$00
SMP0IN	.DB $00
SMP0I1	.DB	$01
SPGEBD
SPGEBD	.DB $03, $03, $03
		.DB	$00, $00, $00
		.DB $01, $01, $01
		
SMVTBL	.DB $31, $41, $52
		.DB $30, $41, $51
		.DB $30, $40, $00
		.DB $40, $42, $63
		.DB $31, $52, $74
		.DB $40, $42, $52
		.DB $31, $41, $51
		.DB $51, $64, $74
		.DB	$51, $42, $00
		.DB $63, $73, $00
		.DB $40, $31, $00
		.DB	$31, $41, $51
		.DB $42, $00, $00
		.DB $42, $52, $00
		.DB $52, $00, $00
		.DB $63, $74, $00
		.DB $40, $00, $00
		.DB $51, $63, $00
		.DB $31, $85, $00
		.DB $63, $74, $00
		.DB $75, $85, $00
		.DB $42, $52, $00
		.DB $74, $85, $00
		.DB $63, $42, $52
		.DB $74, $31, $00
		.DB $74, $51, $00
		.DB $30, $00, $00
		.DB $42, $85, $00
		.DB $30, $40, $85
		.DB $30, $40, $42
		.DB $00, $00, $00
		.DB $00, $00, $00
		.DB $63, $40, $00
		
;BDNDX	.DB	$00, $03, $06, $09, $0C, $0F, $12, $15, $18, $1B, $1E, $21, $24, $27, $2A, $2D
;		.DB	$30, $33, $36, $39, $3C, $3F, $42, $45, $48, $4B, $4E, $51, $54, $57, $5A, $5D, $60
		
		.BS $13
INIT
	LDX #$07			;Initialize right
	LDA #$00			;side
INITLP
	STA WINDO,X			;of display
	DEX					;(plus MOVTIM, MOVTYP)
	BPL INITLP			;to await
	LDA #$C0			;person's
	STA WINDO+4			;move
	LDX #$08
BDINIT
	LDA	BGEBD,X			;Transfer beginning board (in
	STA EBD,X			;Easy-format) to current
	DEX					;board
	BPL BDINIT
	STX FROM			;Indicate no "from" move yet
DISPLT
	LDX #$03			;Clear the
DSPLP
	LDA #$00			;"Display-format"
	STA FLSHR,X			;board and
	DEX					;the flasher-timer
	BPL DSPLP		
	LDY #$02			;Start with 3rd char of board 
	CLC				
NXDIG
	STY TMP 			;(*** was 'TEMP' in original listing ***)
	LDA #$06			;Set up X to start with 
	ADC TMP				;lower segment for
	TAX					;this character 
	LDA #$00			;Clear A so can OR segments 
NXSEG
	ROR					;In this loop, shift the 
	ROR					;segments into place 
	ROR
	ORA EBD,X			;OR 3 for KIM, 1 for person 
	DEX					;point to next higher segment 
	DEX
	DEX
	BPL NXSEG			;Loop till character done
	STA DBD,Y			;Save completed char;
	DEY					;go do next ont to 
	BPL NXDIG			;the left
; Main loop begins here
DISPL0
	DEC FLSHR			;Time to flip KIM bits? 
	BPL LITEST			;No, just show current pattern
	LDA #$30			;Yes, Reset
	STA FLSHR			;timer 
	LDX #$02			;From the 
GETMSK
	LDA DBD,X			;flasher-mask 
	LSR					;patterns
	AND #$49			;for 
	STA MASK,X			;the 
	DEX					;current
	BPL GETMSK			;board
	LDX #$02			;Set X for next loop
	LDA TOG				;Toggle to 
	EOR #$80			;alternate l's and 0's
	STA TOG				;for KIiM' s men
	BMI WNDSET			;Go do 0's
	LDA #$00
ZERMSK
	STA MASK,X			;Clear inasks so 
	DEX					;can do
	BPL ZERMSK			;1's
	LDX #$02
WNDSET
	LDA DBD,X			;Use the
	AND #$49			;masks
	EOR MASK,X			;to flip
	STA WINDO,X			;the bits
	DEX
	BPL WNDSET
;Output to KIM's 7-segment displays
LITEST
	LDA #$7F			;Set directional
	STA PADD			;registers
	LDY #$00		
	LDX #$09			;Start with leftmost char
LITE
	LDA WINDO,Y			;Get character
	STY TEMP		
	JSR CONVD+6			;Output character
	INY
	CPY #$06			;Done all six yet?
	BCC LITE			;Not yet, continue
	JSR $1F3D			;Turn off digits
;Keyboard input begins here
KEYGET
	CLD
	JSR KEYIN
	JSR GETKEY
	CMP #$13			;GO key?
	BNE DACHK		
	JMP INIT			;Yes, start new game
DACHK
	CMP #$11			;DA key?
	BNE GIPROG
	LDX	#$02			;Yes, display (for Data Analysis) 
DALP
	LDA GAMNUM,X		;from left to right
	STA INH,X			;Move# (00,01, or 02)
	DEX					;Board index (Bd # * 3)
	BPL DALP			;Game #. (2 digits each)
	JSR SCANDS			;Keep doing this till DA
	BPL KEYGET			;released; then resume play
GIPROG
	LDX WINDO+4			;Is game still
	CPX #$C0			;in	progress?
	BNE LITEST			;No, Keep showing endgame msg
	CMP #$14			;PC key?
	BEQ KWLINK			;Yes, Person Concedes
	LDX MOVTIM			;Person's turn to move?
	BNE TIMEDS			;No, go time display,
	JSR LEGMOV			;Yes, Did he make legal move?
	BPL PERLM			;Yes, Go execute it
	LDA #$08			;He didn't make a legal move
	STA TMP				;does he have one? Try
LMCHK
	JSR LEGMOV			;each po3ition to see
	BPL TOMVCK
NXFMCK
	DEC TMP				;Try 
	LDA	TMP				;next 
	BPL LMCHK			;position 
	STA MOVTIM			;Tried all, no luck, no legal
	STA MOVTYP			;moves possible, Set KIM
FNMVLP
	JMP DISPL0			;win display after delay
;Continue looking for valid move for person
TOMVCK
	LDA FROM			;Was valid move a "to" move? 
	BPL FNMVLP			;Yes, he can therefore move
	STX FROM			;No, Given this "from" move
	LDA #$06			;try all possible
	STA TMP1			;"to" moves
LTMCHK
	JSR LEGMOV			;Find one? 
	BPL OKMOV			;Yes, He's got a move.
	DEC TMP1			;Try 	
	LDA TMP1			;next 
	BPL LTMCHK			;position 
	STX FROM			;Tried all "to" moves look
	BMI NXFMCK			;for another "from" move. 
;Have found a possible "from-to" move for person
OKMOV
	LDA #$FF			;Has got a move he could make, 
	STA FROM			;so restore FROM and 
	BMI FNMVLP			;continue the game, 
;Person has entered a legal move
PERLM
	LDA #$00			;Clear the "to" indication
	STA WINDO+5			;left from KIM's move. 
	LDA FROM			;Was this a "from" move? 
	BMI FRMDIS			;Yes, display it; save move
	STX PTO				;No, save as person's "to". 
	LDY #$01			;Set "person" indicator
TMINIT
	LDA #$FF			;Set timer, not person's mov
MAKMOV
	STA MOVTIM			;Save move-timer
	STY EBD,X			;Place piece on board. 
	LDA DIGCOD,X		;Get ?-segment code for
	STA WINDO+5			;"to" indication on board
	LDY #$00			;Remove piece from
	LDX FROM			;previous
	STY EBD,X			;board position
	LDA #$FF			;Prepare for next
	STA FROM			;"from" move
	BMI DISX			;Go show this "from" move
;This code displays "from" moves 
FRMDIS
	STX FROM			;Save "from" move
DISX	
	LDA DIGCOD,X		;Use "from" in X to get 7-seg
	STA WINDO+3			;indication
	JMP DISPLT			;Return to main loop.
TIMEDS
	LDA TOG				;Time to decrement move timer? 
	BMI FNMVLP			;Not yet 
	DEC MOVTIM			;Yes. Ready for next move?
	BNE FNMVLP			;Not yet
KWCHK
	LDA MOVTYP			;Has KIM moved 
	LSR					;to either
	CMP #$30			;6,7, or 8
KWLINK	
	BPL KIMWIN			;Yes. KIM won
	LDA PTO				;Has person moved
	CMP #$03			;to 0,1,or 2?
	BMI PERWIN			;Yes. Person won. 
;Try to match current board with stored model	
	LDY #$60			;(#models - 1)*3 = 32*3 = 96
MDLCHK
	LDX BDMDL,Y
	CPX DBD				;First column match? 
	BNE NXBD			;No, try next board model
	LDX BDMDL+1,Y		;Yes, does
	CPX DBD+1			;second column match?
	BNE NXBD			;No, try next board mode
	LDX BDMDL+2,Y		;Yes, does
	CPX DBD+2			;third columh match? 
	BEQ GOTMDL			;Yes, found model. Go get move, 
NXBD
	DEY					;Point to
	DEY					;next board model 
	DEY
	BPL MDLCHK			;and keep comparing,
	BMI PWMSG			;No models found1 have KIM concede the game
;Pick one of the remaining moves for this position
GOTMDL	
	LDA TIMER			;Use the timer to 
	AND #$03			;arbitrarily select
	TAX					;move o, 1, or 2
	BEQ POK				;(This code picks #2 
	DEX					;half the time.) 
POK
	LDA #$02			;lnititialize the counter for
	STA TMP				;how many moves to try (3)
MVSLLP
	STX TMP1			;Temporary move number
MVLP1
	LDA #$2D			;(*** was LDA ADMVTB in original listing ***)
	CLC
	ADC TMP1			;Set ADL of pointer to pick
	STA POINTER			;up this move.
	LDA (POINTER),Y	
	BNE GOTMOV			;Got a valid move -- use it!
	DEC TMP
	BMI PERWIN			;No moves left; KIM resigns, 
	DEC TMP1			;Try next move 
	BPL MVLP1			;in the set, (May try
	LDX #$02			;in order 2,1,0; 1,0,2;
	BPL MVSLLP			;or 0,2,1) 
PERWIN
	LDY BDNDX			;Person has won. ************ 
	CLC					;Compute the ADL
	LDA #$2D			;(*** was LDA ADMVTB in original listing ***)
	ADC MOVNO			;of KIM's 
	STA POINTER			;last move. (POINTER+1 = 0) 
	LDA #$00			;Wipe out the last
	STA (POINTER),Y		;move KIM made,
PWMSG
	LDA #PWAD			;Get address of "person won"
	BPL STAD			;message
KIMWIN
	LDA	#KWAD			;Get "KIM won" msg address. 
STAD
	STA MPOINT			;Point to message address (ADL) 
;Display en-of-game-message
	LDY #$05
FILWIN
	LDA (MPOINT),Y		;Store the six-letter
	STA WINDO,Y			;message in the window.
	DEY
	BPL FILWIN			
	INC GAMNUM			;Increment game number.
	JMP LITEST			;Show msg and wait for GO
;Make KIM's chosen move
GOTMOV
	STA MOVTYP			;Save move for later checks, 
	STY BDNDX			;save board pointer. 
	LDX TMP1			;Pick up
	STX MOVNO			;move# (=0,1, or 2)
	PHA					;Save 2 copies of move type
	PHA
	LSR
	LSR
	LSR
	LSR
	TAX					;Place "to" move in X
	PLA
	AND #$0F			;Extract and save
	STA FROM			;"from" move
	LDY #$03			;Indicate KIM move being made
	PLA					;Is upper half-byte of...
	LSR					
	CMP #$30			;move a 6,7, or 8?
	BMI NOKWIN			;No, KIM hasn't won
	JMP TMINIT			;Yes. Show winning move
NOKWIN
	LDA #$00			;Indicate it's person's
	JMP MAKMOV			;move, and make KIM's
;Subroutine to test for legal move
;Call with move in A
;Returns with 	X = $FF if illegal move
;				X = move if legal
		.DB $00, $00
LEGMOV
	CMP #$09			;Is move 0 to 8? 
	BCS MOVFNG			;No, illegal
	TAX
	LDA EBD,X			;Extract player indicator from
	ROR					;board: 1 player, 3 KIM
	ROR	
	BPL TOCHK			;Nobody here, but OK if "to"
	LDA FROM			;Is this a "from• move?
	BPL PTOMOV			;No. Go see if legal "to"
	BCS MOVFNG			;Yes, but KIM's here! Bad
MOVOK
	TXA					;Return, Legal move was made
	RTS					;(or found possible)
PTOMOV
	TXA					;Place "to• move in A
	BCC MOVFNG			;Person here! Can't capture! 
	ASL					;KIM here. A capture. Can 
	ASL					;only be one of 8 possible
	ASL
	ASL
	ORA FROM			;moves, Format "T0:FROM"
	LDY #$07			;and test against
CAPCHK
	CMP CAPSET,Y		;each possibility. 
	BEQ MOVOK			;Found it! Move is OK, 
	DEY
	BPL CAPCHK
MOVFNG
	LDX #$FF			;Move illegal, Set indicator
	RTS					;(Second of two return points
NOCAP
	TXA					;If here, not capture, C=O, 
	ADC #$03			;Is move + 3 = FROM? 
	CMP FROM
	BNE MOVFNG			;No, Illegal move. 
	BEQ MOVOK
TOCHK
	LDY FROM			;Space here. "To" move? 
	BMI MOVFNG			;No, Illegal move,
	BPL NOCAP			;Yes, See if valid move. 
;Set of all possible "capture" moves by person
;packed in "TO;FROM" format
CAPSET
	.DB $13, $04, $24, $15, $46, $37, $57, $48

**Comment by jefftranter** [comment]
Looks like a good game, but it is available elsewhere so I don't plan to check it into my repository.
