### ISSUE TITLE
CEGMON source comments added

### ISSUE THREAD

**Issue by douggilliland** [jefftranter/6502#8]
Hi Jeff,

I took the CEGMON source you have here and added the labels from the user's manual. It's up at:

https://github.com/douggilliland/MultiComp/blob/master/MultiComp_On_Cyclone%20IV%20VGA%20Card/UK101_16K_64x32_Video/Components/ROMs/cegmon.s

There's a really nice BLOG post by one of the CEGMON authors at:

http://weblog.tetradian.com/2014/03/16/cegmon-a-blast-from-the-past/

Doug

**Comment by jefftranter** [comment]
Thanks for the info and for making those changes. I'll apply them to my
version.

Regards,
Jeff
